# Testing the code base against a specific Meilisearch feature
name: Beta tests

# Will only run for PRs and pushes to *-beta
on:
  push:
    branches: ['!bump-meilisearch-v*.*.*-beta', '**-beta']
  pull_request:
    branches: ['!bump-meilisearch-v*.*.*-beta', '**-beta']

jobs:
  grep-docker-version:
    runs-on: ubuntu-latest
    outputs:
      docker-version: ${{ steps.grep-step.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Grep docker beta version of Meilisearch
        id: grep-step
        run: |
          MEILISEARCH_IMAGE=$(sh .github/scripts/beta-docker-version.sh)
          echo $MEILISEARCH_IMAGE
          echo ::set-output name=version::$MEILISEARCH_IMAGE
  cypress-run:
    runs-on: ubuntu-latest
    needs: ['grep-docker-version']
    # Only test on Google Chrome
    services:
      meilisearch:
        image: getmeili/meilisearch:${{ needs.grep-docker-version.outputs.docker-version }}
        env:
          MEILI_MASTER_KEY: 'masterKey'
          MEILI_NO_ANALYTICS: 'true'
        ports:
          - '7700:7700'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn --dev && yarn --cwd ./tests/env/react
      - name: Setup Meilisearch Index
        run: yarn local:env:setup
      - name: Run local browser tests
        uses: cypress-io/github-action@v3
        with:
          wait-on: 'http://localhost:7700'
          # Tests are only done on one playground to avoid long testing time
          start: yarn local:env:react
          env: playground=local
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

  tests:
    runs-on: ubuntu-latest
    needs: ['grep-docker-version']
    services:
      meilisearch:
        image: getmeili/meilisearch:${{ needs.grep-docker-version.outputs.docker-version }}
        env:
          MEILI_MASTER_KEY: 'masterKey'
          MEILI_NO_ANALYTICS: 'true'
        ports:
          - '7700:7700'
    strategy:
      fail-fast: false
      matrix:
        node: ['14', '16', '18']
    name: integration-tests (Node.js ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Meilisearch (${{ needs.grep-docker-version.outputs.docker-version }}) setup with Docker
        run: docker run -d -p 7700:7700 getmeili/meilisearch:${{ needs.grep-docker-version.outputs.docker-version }} meilisearch --master-key=masterKey --no-analytics
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build project
        run: yarn build
