name: Dependabot auto-merge

on:
  pull_request:
    branches:
      - 'dependabot/**'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{secrets.GITHUB_TOKEN}}
